{{- if .Values.runOnce }}
apiVersion: batch/v1
kind: Job
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: {{ include "model-manager-loader.fullname" . }}
  labels:
    {{- include "model-manager-loader.labels" . | nindent 4 }}
spec:
  {{- if not .Values.runOnce }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "model-manager-loader.selectorLabels" . | nindent 6 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "model-manager-loader.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ sha256sum (toJson .Values) }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.runOnce }}
      restartPolicy: Never
      {{- end }}
      serviceAccountName: {{ include "model-manager-loader.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: model-manager-loader
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ default .Chart.Version .Values.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - run
        - --config
        - /etc/config/config.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: tmp
          mountPath: /tmp
        - name: tmp
          mountPath: /.ollama
        {{- with .Values.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        env:
        {{- with .Values.global.awsSecret }}
        {{- if .name }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .name }}
              key: {{ .accessKeyIdKey }}
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .name }}
              key: {{ .secretAccessKeyKey }}
        {{- end }}
        {{- end }}
        {{- with .Values.huggingFaceSecret }}
        {{- if .name }}
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .name }}
              key: {{ .apiKeyKey }}
        {{- end }}
        {{- end }}
        - name: HF_HOME
          value: {{ .Values.downloader.huggingFace.homeDir }}
        {{- with .Values.global.worker.registrationKeySecret }}
        {{- if .name }}
        - name: LLMO_CLUSTER_REGISTRATION_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .name }}
              key: {{ .key }}
        {{- end }}
        {{- end }}
        # We have to do this because the container names can have '-' characters
        {{- with index .Values "model-manager-loader"  "env" }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with index .Values "model-manager-loader"  "envFrom" }}
        envFrom:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "model-manager-loader.fullname" . }}
      - name: tmp
      {{- if .Values.persistentVolume.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolume.existingClaim | default (include "model-manager-loader.fullname" .) }}
      {{- else }}
        emptyDir:
      {{- end }}
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
